kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv
  labels:
    type: manual
spec:
  storageClassName: gold
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/brigade/share"


apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: <ClusterIP>
    path: "/"

