# Default values for my-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: gcr.io/my-project-70505/dhirwanashish/test
  tag: v2
  pullPolicy: IfNotPresent
port: 3005

service:
  type: LoadBalancer

favorite:
  drink: coffee
  food: pizza
pizzaToppings:
  - mushrooms
  - cheese
  - peppers
#  - onions
#persistentVolumeClaim:
#  claimName: mypvc

#claimName: mypvc
